GAME_WINDOW_WIDTH = 800
GAME_WINDOW_HEIGHT = 600

BALL_HEIGHT = 8
BALL_WIDTH = 8
BALL_SPEED = 5

PADDLE_HEIGHT = 80
PADDLE_WIDTH = 5
PADDLE_SPEED = 10

GAME_FONT = "freesansbold.ttf"
GAME_FONT_SIZE = 16