GAME_WINDOW_WIDTH = 800
GAME_WINDOW_HEIGHT = 600

BALL_HEIGHT = 8
BALL_WIDTH = 8
BALL_SPEED = 7
BALL_BOUNCE_ACCELERATION = 0.1

PADDLE_HEIGHT = 50
PADDLE_WIDTH = 5
PADDLE_SPEED = 11

SCORE_LIMIT = 1

MIDLINE_WIDTH = 4
SCORE_Y = 50
SCORE_X_R = 550
SCORE_X_L = 200

GAME_FONT = "impact.ttf"
GAME_FONT_SIZE = 24
SCORE_FONT_SIZE = 48


#GAMESTATES
GAMESTATE_GAMEPLAY = 0
GAMESTATE_MENU = 1
GAMESTATE_OPTIONS = 2
GAMESTATE_EXIT_PROMPT = 3
GAMESTATE_EXIT_PROMPT_FROM_GAMEPLAY = 4